services:
  redis:
    image: "redis:7.2.4-alpine3.19"
    command: "redis-server --requirepass $REDIS_PASSWORD"
    networks:
      - api_network

  azurite:
    build:
      context: functions
      dockerfile: Dockerfile-azurite
    networks:
      - api_network
    volumes:
      - azurite:/opt/azurite
      - certs:/etc/ssl/certs

  postgres:
    image: "postgres:17.1-alpine3.20"
    networks:
      - api_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=$DB_USER"
      - "POSTGRES_PASSWORD=$DB_PASSWORD"
      - "POSTGRES_DB=$DB_NAME"
    ports:
      - "$DB_PORT_EXT:$DB_PORT"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$DB_USER", "-d", "$DB_NAME"]
      interval: 1s
      timeout: 3s
      retries: 5

  api:
    build:
      context: api
      dockerfile: Dockerfile-dev
    volumes:
      - ./api:/api
      - certs:/etc/ssl/certs
    networks:
      - api_network
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      redis:
          condition: service_started
      postgres:
          condition: service_healthy

  functions:
    build:
      context: .
      dockerfile: ./functions/Dockerfile-dev
    volumes:
      - ./api:/api
      - ./functions:/functions
      - certs:/etc/ssl/certs
    networks:
      - api_network
    ports:
      - 7071:7071
    env_file:
      - .env
    depends_on:
      - azurite

volumes:
  pgdata:
    driver: local
  certs:
    driver: local
  azurite:
    driver: local

networks:
  api_network:
